version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: |
          docker build -t swhurl/website:$CIRCLE_SHA1 .
          docker build -t swhurl/website-test -f Dockerfile.test .
      - run: |
          docker network create -d bridge swhurl
          docker run -d --name website --net swhurl swhurl/website:$CIRCLE_SHA1
          docker run --name website-test --net swhurl -e DOCKER_NETWORK=true swhurl/website-test
          docker stop website
          docker network rm swhurl
      - run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push swhurl/website:$CIRCLE_SHA1
        
