version: 2
jobs:
  build_test: 
    machine: true
    steps:
      - checkout
      - run: |
          docker build -t swhurl/website:$CIRCLE_SHA1 .
          docker build -t swhurl/website-test -f Dockerfile.test .
      - run: |
          docker network create -d bridge swhurl
          docker run -d --name website --net swhurl swhurl/website:$CIRCLE_SHA1
          docker run --name website-test --net swhurl -e DOCKER_NETWORK=true swhurl/website-test
          docker stop website
          docker network rm swhurl
  build_test_push:
    machine: true
    steps:
      - checkout
      - run: |
          docker build -t swhurl/website:$CIRCLE_SHA1 .
          docker build -t swhurl/website-test -f Dockerfile.test .
      - run: |
          docker network create -d bridge swhurl
          docker run -d --name website --net swhurl swhurl/website:$CIRCLE_SHA1
          docker run --name website-test --net swhurl -e DOCKER_NETWORK=true swhurl/website-test
          docker stop website
          docker network rm swhurl
      - run: |
          echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
          docker push swhurl/website:$CIRCLE_SHA1
  deploy_staging:
    machine: true
    steps:
      - run: |
          echo "staging: branch == master"
          echo "sha1: '$CIRCLE_SHA1'"
          echo "tag: '$CIRCLE_TAG'"
          echo "deploy: swhurl/website:$CIRCLE_SHA1"
          ssh sam@swhurl.com
          kubectl describe pods swhurl-website-staging -o yaml | sed -r 's/website:(.*)/website:$CIRCLE_SHA1/g' | kubectl apply -f -
          exit
  deploy_prod:
    machine: true
    steps:
      - run: |
          echo "production: tag == $CIRCLE_TAG"
          echo "sha1: '$CIRCLE_SHA1'"
          echo "tag: '$CIRCLE_TAG'"
          docker pull swhurl/website:$CIRCLE_SHA1
          docker tag swhurl/website:$CIRCLE_SHA1 swhurl/website:$CIRCLE_TAG
          docker push swhurl/website:$CIRCLE_TAG
          echo "deploy swhurl/website:$CIRCLE_TAG"
        
workflows:
  version: 2
  build_test:
    jobs:
      - build_test:
          filters:
            branches:
              ignore: master
  deploy_staging:
    jobs: 
      - build_test_push
      - deploy_staging:
          requires:
            - build_test_push
          filters:
            branches:
              only: master
  deploy_prod:
    jobs:
      - deploy_prod:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v(.*)/
